const types = {
  ON_SEND_LOGIN: "ON_SEND_LOGIN",
  ON_SEND_LOGIN_ERROR: "ON_SEND_LOGIN_ERROR",
  ON_SEND_LOGOUT: "ON_SEND_LOGOUT",
  ON_SEND_LOGOUT_ERROR: "ON_SEND_LOGOUT_ERROR"
};

export default types;
