const types = {
  ON_SEND_LOGIN: 'ON_SEND_LOGIN',
  ON_EMAIL_DATA: 'ON_EMAIL_DATA',
  ON_GET_USERS: 'ON_GET_USERS',
  ON_ADD_USERS: 'ON_ADD_USERS',
  ON_SEND_LOGOUT: 'ON_SEND_LOGOUT',
  ON_GET_COLLECTION: 'ON_GET_COLLECTION',
  ON_SET_COLLECTION: 'ON_SET_COLLECTION',
  ON_ADD_COLLECTION: 'ON_ADD_COLLECTION',
  ON_DELETE_COLLECTION: 'ON_DELETE_COLLECTION',
  ON_GET_TOTAL_DATA: 'ON_GET_TOTAL_DATA',
  ON_SET_UPLOAD: 'ON_SET_UPLOAD',
  ON_GET_DOWNLOAD: 'ON_GET_DOWNLOAD',
  ON_GET_CSV: 'ON_GET_CSV',
  ON_SHARE_RECEIPT: 'ON_SHARE_RECEIPT'
  // ON_SET_EXPENSES: 'ON_SET_EXPENSES',
  // ON_GET_USERS: 'ON_GET_USERS',
  // ON_SET_USERS: 'ON_SET_USERS',
  // ON_GET_BANKBOOK: 'ON_GET_BANKBOOK',
  // ON_SET_BANKBOOK: 'ON_SET_BANKBOOK'
};

export default types;
